name: pytest
description: Run 'pytest'

branding:
  icon: activity
  color: gray-dark

inputs:
  token:
    description: GitHub Personal Access Token
    default: ${{ github.token }}
  python-version:
    description: The version of Python to set UV_PYTHON to
    default:
  with-requirements:
    description: Run with the packages listed in the given files
    default:
  resolution:
    description: The strategy to use when selecting between the different compatible versions for a given package requirement
    default: highest
  prerelease:
    description: The strategy to use when considering pre-release versions
    default: disallow

runs:
  using: composite
  steps:
    - name: Check out repo
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install 'uv'
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ inputs.python-version }}

    - name: Run 'pytest'
      run: |
        args=()
        if [ -n "${{ inputs.with-requirements }}" ]; then
          args+=(--with-requirements "${{ inputs.with-requirements }}")
        fi
        args+=(--resolution "${{ inputs.resolution}} ")
        args+=(--prerelease "${{ inputs.prerelease}} ")
        uv run "${args[@]}" pytest --numprocesses auto
      shell: bash
